// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './models.gen';

export class AuthService {
    /**
 * Login
 * Login
 * @returns LoginResponse Login response
 * @throws ApiError
 */
    public static login(data: $OpenApiTs['/customer/auth/login']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/customer/auth/login']['post']['res'][201]> {
        const { requestBody, cache } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/customer/auth/login',
    path: {
        cache
    },
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
    /**
 * Register
 * Register
 * @returns RegisterResponse Register response
 * @throws ApiError
 */
    public static register(data: $OpenApiTs['/customer/auth/register']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/customer/auth/register']['post']['res'][201]> {
        const { requestBody, cache } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/customer/auth/register',
    path: {
        cache
    },
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
}

export class BlogService {
    /**
 * Get blog detail
 * Get blog detail
 * @returns GetBlogDetailResponse A blog
 * @throws ApiError
 */
    public static getBlogDetail(data: $OpenApiTs['/customer/blog/{id}']['get']['req']): CancelablePromise<$OpenApiTs['/customer/blog/{id}']['get']['res'][200]> {
        const { id, cache } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/customer/blog/{id}',
    path: {
        id,
        cache
    }
});
    }
    
    /**
 * Get blog list
 * Get blog list
 * @returns GetListBlogResponse An array of blogs
 * @throws ApiError
 */
    public static getBlogs(data: $OpenApiTs['/customer/blog']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/customer/blog']['get']['res'][200]> {
        const { select, skip, take, relations, order, cache } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/customer/blog',
    path: {
        cache
    },
    query: {
        select,
        skip,
        take,
        relations,
        order
    }
});
    }
    
}

export class CustomerService {
    /**
 * Get current customer
 * Get current customer
 * @returns GetMeResponse Get current customer success
 * @throws ApiError
 */
    public static getMe(data: $OpenApiTs['/customer/me']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/customer/me']['get']['res'][200]> {
        const { cache } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/customer/me',
    path: {
        cache
    }
});
    }
    
}

export class TagService {
    /**
 * Get tag list
 * Get tag list
 * @returns GetTagListResponse An array of tags
 * @throws ApiError
 */
    public static getTags(data: $OpenApiTs['/customer/tag']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/customer/tag']['get']['res'][200]> {
        const { select, skip, take, relations, order, cache } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/customer/tag',
    path: {
        cache
    },
    query: {
        select,
        skip,
        take,
        relations,
        order
    }
});
    }
    
}